# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
   # imports =
    # [ (modulesPath + "/installer/scan/not-detected.nix")
    # ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme"
                                         "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/64c3d450-3759-4ab9-b204-f80dd48750ca";
      fsType = "btrfs";
    };

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/8AFE-DA90";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/6a8e0faf-d646-4e76-83b2-296591470256"; }
    ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
