# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
   # imports =
    # [ (modulesPath + "/installer/scan/not-detected.nix")
    # ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme"
                                         "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/e7adcc9d-9045-408d-bd80-c998062bbcfb";
      fsType = "btrfs";
    };

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/8AFE-DA90";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/3b8ca042-1293-4c1c-9420-1ddccbd09713"; }
    ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
